version: "3.8"

services:
  db:
    restart: always
    image: postgres:latest
    container_name: "linkdb"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty

  shortener:
    restart: always
    build: ./
    container_name: "linkapi"
    command: ./wait-for-postgres.sh db ./shortener
    env_file: ./configs/.env
    environment:
      DB_PASSWORD: "qwerty"
    ports:
      - "8000:8000"
    depends_on:
      - db
